# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python

Numpy utilized C-base libraries which greatly enhances the speed of calculations


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np



# Numpy Arrays

NumPy arrays are a core data structure in Python. Numpy arrays can be described as: vectors and matrices. What is the difference between a vector and matrix?

## Creating NumPy Arrays

### From a Python List


In [2]:
my_list = [100,210,326]
my_list

[100, 210, 326]

In [3]:
np.array(my_list)

array([100, 210, 326])

In [4]:
first_matrix = [[1,2,3],[9,10,15],[27,38,10]]
first_matrix

[[1, 2, 3], [9, 10, 15], [27, 38, 10]]

In [5]:
np.array(first_matrix)

array([[ 1,  2,  3],
       [ 9, 10, 15],
       [27, 38, 10]])

### arange

Return evenly spaced values within a given interval.

In [6]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.arange(0,14,2)

array([ 0,  2,  4,  6,  8, 10, 12])

### zeros and ones

Generate arrays of zeros or ones

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [12]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [13]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

## eye

Creates an identity matrix

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [15]:
np.random.rand(3)

array([0.64369926, 0.47122788, 0.71425537])

In [ ]:
## press tab to get the other potentials

In [16]:
np.random.rand(4,4) # here you are creating a 4x4 matrix

array([[0.4083396 , 0.14430711, 0.05510743, 0.7861857 ],
       [0.60030633, 0.60622527, 0.81170431, 0.59417311],
       [0.66323402, 0.55980554, 0.56763057, 0.91194292],
       [0.58979629, 0.36540797, 0.74421037, 0.05747085]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [17]:
np.random.randn(3)

array([-1.63371064,  1.24001459,  0.83491152])

In [18]:
np.random.randn(5,5)

array([[ 0.86488719,  1.73644238,  0.31094056, -1.43475211, -0.80143514],
       [-1.00142053, -1.88677415,  1.92462611,  0.69741653,  0.9512228 ],
       [-0.83515812, -1.31520975, -0.12904472, -0.01501337,  0.44703728],
       [ 0.59719181,  0.83938027, -0.01376329, -0.15282247,  0.01370276],
       [-0.32557394,  2.27829214,  0.33641242,  1.45549171, -1.10229371]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [19]:
np.random.randint(1,20)

17

In [20]:
np.random.randint(1,50,10)

array([13, 37, 14,  7, 12, 22, 16, 38, 27, 35])

In [25]:
np.random.randint(1000,1000000,20)

array([ 68964, 792239, 107598, 724087, 708479, 721836, 198524, 544734,
       401808, 144695, 256770, 761554, 701787, 786403, 454995, 187379,
       966890, 612272, 208557,  61093])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [26]:
arr = np.arange(20)
rarr = np.random.randint(0,50,5)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
rarr

array([38, 39, 29, 44, 45])

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
rarr

array([38, 39, 29, 44, 45])

In [31]:
rarr.max()

45

In [32]:
rarr.argmax()

4

In [33]:
rarr.min()

29

In [34]:
rarr.argmin()

2

## Shape

Shape is an attribute that arrays have:

In [35]:
# Vector
arr.shape

(20,)

In [36]:
arr.reshape(1,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [37]:
arr.reshape(1,20).shape

(1, 20)

In [38]:
arr.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [39]:
arr.reshape(20,1).shape

(20, 1)

### dtype

You can also grab the data type of the object in the array:

In [40]:
arr.dtype

dtype('int32')