# NumPy Selection 

This exercise will demonstrate how to select elements from an array

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,15)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Brackets for selection


In [4]:
#Get a value at an index
arr[5]

5

In [5]:
#Get values in a range
arr[1:6]

array([1, 2, 3, 4, 5])

In [6]:
#Get values in a range
arr[0:4]

array([0, 1, 2, 3])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:6]=10

#Show
arr

array([10, 10, 10, 10, 10, 10,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,15)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
#Important notes on Slices
sliced = arr[0:6]

#Show slice
sliced

array([0, 1, 2, 3, 4, 5])

In [10]:
#Change Slice
sliced[:]=20

#Show Slice again
sliced

array([20, 20, 20, 20, 20, 20])

Now note the changes also occur in our original array!

In [11]:
arr

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Indexing a matrix

In [13]:
arr_2d = np.array(([10,20,30],[60,70,80],[90,110,145]))

#Show
arr_2d

array([[ 10,  20,  30],
       [ 60,  70,  80],
       [ 90, 110, 145]])

In [14]:
#Indexing row
arr_2d[1]


array([60, 70, 80])

In [15]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

60

In [16]:
# Getting individual element value...I suggest this method of using a comma, rather than double brackets
arr_2d[1,0]

60

In [17]:
#Shape bottom row
arr_2d[2]

array([ 90, 110, 145])

## Conditional Selection

This a very important topic that you will most likely utilize in your work

In [18]:
arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [19]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [20]:
bool_arr = arr>4

In [21]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [22]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
arr[arr>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
x = 8
arr[arr>x]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])